global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#yury_yashkin'