version: '3.3'
services:
  post_db:
    #container_name: my-mongodb-container
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    #build: ./ui
    #container_name: my-ui-container
    image: ${USER_NAME}/ui #:${UI_SERVICE_VERSION}
    ports:
      - ${UI}:9292/tcp
    networks:
      - front_net

  post:
    #build: ./post-py
    #container_name: my-post-container
    image: ${USER_NAME}/post #:${POST_SERVICE_VERSION}
    networks:
      - back_net
      - front_net

  comment:
    #build: ./comment
    #container_name: my-comment-container
    image: ${USER_NAME}/comment #:${COMMENT_SERVICE_VERSION}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
  front_net:
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
